quarkus:
  log:
    category:
      "com.onblocktrust":
        level: DEBUG
    console:
      enable: true
    file:
      enable: false
    handler:
      gelf:
        enabled: false

  live-reload:
    instrumentation: true

  http:
    port: 9003

  datasource:
    db-kind: h2
    username: sa
    password:
    jdbc:
      url: jdbc:h2:tcp://localhost/~/app-home/block-trust/db/h2-dev;AUTO_SERVER=true;DB_CLOSE_DELAY=-1
      max-size: 10
