app:
  id: blocktrust-payment-service
  name: Blocktrust Payment Service

#payu;
#  merch
quarkus:

  tls:
    trust-all: true;

  rest-client:
    extensions-api:
      url: https://stage.code.quarkus.io/api
      scope: javax.inject.Singleton

  log:
    category:
      "com.onblocktrust":
        level: INFO
    console:
      enable: false
    file:
      enable: true
      path: /tmp/${app.id}.log
    handler:
      gelf:
        enabled: true
        host: localhost
        port: 12201

  http:
    cors: true

  datasource:
    db-kind: postgresql
    username: db_username
    password: db_password
    jdbc:
      url: jdbc:postgresql://db_host_name:db_port/db_name
      max-size: 10

  hibernate-orm:
    database:
# https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.scripts-database-scripts-related-configuration
# allowed values: none / create / drop-and-create / drop / update / validate
      generation: validate

  swagger-ui:
    theme: original
  #    always-include: true

  smallrye-openapi:
    info-title: ${app.name} API
    info-version: 0.0.1

hibernate:
  validator:
    allow_parameter_constraint_override: true

