app:
  id: blocktrust-payment-service
  name: Blocktrust Payment Service
  gitTag: tag_id

  payu:
#    merchant-key: vqIo0Y
#    merchant-salt1: fqrpOXlW3WqzLowixo8E2fd4eAni8zvc
#    merchant-salt2: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDSQ5UoQaNHi7SdYBGwoWrgZnJoN/wPBd5E/8IPJBwinzhaCRUoXq1CuebqxBI2hIlO7ZC+Fhifn8aNQ7Yp48hI/FslqiS3x1pP3dwnpYzhNLo8u/Mm3ZsHUDXB7PD/HZFQF5RBWNbt2k6LBp7yfkw3ZF+M2ODz/4Zo5VrVCazbF5PrNCwvKCryBK7Ds013hskEsY+OASUmQAS1rrggmZrqM8uYBnpIlOP2ePBKC41rpAPF4mgMMqboye1gbk+b8wNTTV77O3eveznR9la9YhoLOgj1oaOIN93Yt/+iPuhpqoBiZqMXB+SvKu8Q0beWzWGQPcjDsjokTDCV6N2VJFdRAgMBAAECggEAf/X5NEKd59Cx3oS0v1W9AUvXnG1VzJ65oiw0IZrMNJXJaaHVangT4WPZkE4690q5dXtGdyhjW+GUqCvpFJ03KpPJtKZTKjT8VVajwM0Ta4r3PDb1x1VeH5lE3fwgvmF0KdXvt8UlKCOPYTRqTxFluOAw9jqWzGdZmUTbfoMg20PnsDwcXM2eIBwRTygStdsiUq96VyPp80zCeXkMiAPrZODoUUlRGYl1dt8lMnfWF29NcLr/T+tSw6TjWPGBcLRGT6iYfVpv688DcVjwLQk3Ok6pQHto+eS7TdE2SciWMtYOGHdKmRQXuLWVRcA9Sz5AkiOF6IiBVYcpTE6+2BjHAQKBgQDpOO+CDpWA0nzA/Co5oXPFplhhXV757zUjEEJhgD0hcJHsXnNgOSwkwD4xbJlm9ChgelUgU6MWJyoDlfGOpDKpZpiRLP/dSWiUYcNuXPb1ZND48xm2rNgXGk0LlXfq7g4v7HN4n0zK+UNg8grKrgXfyC0K5gATRD4ZSGnj/ys+OQKBgQDmzKMd9uqOGet8Oe6VEa2zWvKhTCRbYqVhALmAwFlE3PBtmfIvRk92yDXkhONYaIF8bH1I4hxfZBhIFNxZo7vJm+PdP8WsEvIfG3HtwW7w+G2cGGAr+2emlUIhWJnn64YgJqHwG3cb/Y21H74zxixOWmIuRLZGAVoEluYj7jFh2QKBgQCJKRn65Dbax2/lU6hFsoVS9Yy+3lnwJdWbZIGVtAS/uOOpHrc+HQGwL3ukN5lUaj2g1/FejLG6Ypgb+cBRwpGk/Ri3ML7d1sFxmrmEG5qGIZ+g+d/ihm6jz60GJgabnRus5aPXieBw8v3EczUTlBsSTDjpUvEyY40d82+LTlORSQKBgE6dN5Z2S3C5rXdz+Cs4iVUFTo3YdK3YDQLcj1MmsYF+TDrY7CBkL58DFTBQf2vWtPxfq9EOi6GGY6rxyBiUZ9uFSPlMxpUVIvmrjIPylkpoJFW+C8wPZz/bqVnYZxwTIm2DGzfA8zJKjGE8fbn+74qEyNp/tyJjRXk4uQ1WDeYJAoGAM0nx+a15u/h9SP5sV/MsB45xCtDMTjvu/QH7t1Klw4kpx/LWyIncdcu4ox8XOHUaDX2qG15dFsTmDxVHDg/VADxvo0j/jTVpGn6mjCuXFPOmumWu427jIWij/9BN7qtuoPmguXZfAP6ybawZVX4cOAuEsvklHjfDquv6TBKt6Dk=

    merchant-key: gtKFFx
    merchant-salt1: eCwWELxi
    merchant-salt2: wia56q6O

#    merchant-key: 6KLG6s
#    merchant-salt1: FBTMEOSiqiGePxedf9sMYyXxCObmKRkW
#    merchant-salt2: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDcZG5CkJhcjcV2+T6hm1b861QgbW2h7smeYxd3+KevSkxnE+2xTWZwcwxPdgS6LuM3F8G6uBkaV0/wT5kZ5LW+TlK6ygr2TBfJX6v2OTy81CId8I7UYTp0BQlOYjql0VhlTvru0mHkGTyj849qZEOmQ4OFrY65eZJeCxsVAOjy1rOKWoPq1IkNVfj8bRb0dW7ZtuiIWj2y/E3nrnNH/muY5db8hGLsze3jwYv4/zgoOk7na/Z9m+t+n9RlqZyAo1ZhLvS61CLkq8frBRjYIX76a55qCBCZ7fbgjsNOp23jY3g3MxCARVqd5n7fGxGfdleDrFo+bjfnMD2Tu/PUfuF7AgMBAAECggEBAJ4WpEi3M7NgNn7K9rQxm0o8+9Fu7S80/AbTCaiTAqVoZDmkP+HopUyQGgp9m5J5w55nOh3XpJoSe1Ljpey+8+cYg5tdBlP57S4TpGQwVnMUr4xOXAXX4HgMjMpfB7ad3gx9hN3+px1ZRPhN41frp+MBlrwy7Kf6npU63ihIyNA3AShIxhfrZvQu0Zs0Tcnabg9cIh58k0+I6MqI8wRKMQKIui0OThPkBmw8og+mcgE+ppupUQfVN4gWetcwICuf5TJroqtkw0ZQc6aPlZkKC9GR6qXxDhOmNu0vP1cfwkErtPgm+uouReLz2GMw3n2xlTjNLU1Gk3Yn0R+g3JFvaSECgYEA8lwzKx4b07uzkkmANheWpNBehB1kXHGDKMKv1tO6OCGNf/FCR6jCrfArynB3RrHOcQRJAzjiyac3uJs3AvpZXIzdlYGS2y1y2iDb3/cWtKgEYCce0+XdVOMqGQrUinzWX72gvmKE0bTyG677ucFztNjhfSa7K7z36UbOmdaC6UkCgYEA6Mu6udOV9dSPV7DKhZT5waxSVuuM3foUXbpTm/qlx66Th8XYaUHgQpi+7GksFn6kBek8bqDA2MDy4WS6ge90euwWyulFuyWQScWn/DNDM9xVCCHj6ULkUuaFQoi/s4Go6UXTyFW/qcMpzU6iDSvv6IWYsp/7n4UtXZ2WlFiZmKMCgYBpVP78F1rau/JAeudZGwli2hip7KhIsSDi3zJS+LQvXw3DdFRtFoB93ir6EcUVGYPyhH1DBD80ixNhjTvsdGfQHHzVVHpB/c+z06IcBaR9oaQ9MeNpDrcSBKSwO4/CHJ2DAMRS2jiFd9HdjEBlLBmgmL3viZzBVqCcZyS1oZBF2QKBgHRlaPeA03oWzZUK0Df6ROaRQpozLDvQzl4Oy78xk7JDl4BLa+k1BuxFczDBZUnaCCjsdUrbFZFK6CXKN3bAQ30yjjLmb/ci0QIR0exHtVI42Es4prv6ti69E+Qwe6lFKy93umxwc2RuMHh22I+9aDbalX66fxVDgWtNX/zMUAABAoGBAL+mJiRSi/tRCr2nKVoSmj8lUZsuD1hRoUooZpnOM1kSjsaPZ9SAX+IO8jk4iokF+BWvAIXEZ8p9wgPogAYUH+e7m+dBMPK3KPKUVr5L6hf/xgRZ/6f/CTr9IXjDFf0oMpg0TiKDnI7IPcdgCrlZ+OwbWtBy/BV5rjnYtRe64gTl

  razorpay:
    key: rzp_test_cwpsi4iy7TJC8y
    secret: G7j69HDTNPC004qCtXp2oztq

quarkus:

  tls:
    trust-all: true

  rest-client:
    extensions-api:
      url: https://stage.code.quarkus.io/api
      scope: javax.inject.Singleton

  log:
    category:
      "com.onblocktrust":
        level: INFO
    console:
      enable: false
    file:
      enable: true
      path: /tmp/${app.id}.log
    handler:
      gelf:
        enabled: true
        host: localhost
        port: 12201

  http:
    cors: true

  datasource:
    db-kind: postgresql
    username: db_username
    password: db_password
    jdbc:
      url: jdbc:postgresql://db_host_name:db_port/db_name
      max-size: 10

  hibernate-orm:
    database:
# https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.scripts-database-scripts-related-configuration
# allowed values: none / create / drop-and-create / drop / update / validate
      generation: validate

  swagger-ui:
    theme: original
  #    always-include: true

  smallrye-openapi:
    info-title: ${app.name} API
    info-version: 0.0.1

hibernate:
  validator:
    allow_parameter_constraint_override: true

