
quarkus:
#  log:
#    category:
#      "com.blocktrust":
#        level: DEBUG
#    console:
#      enable: true
#    file:
#      enable: false
#    handler:
#      gelf:
#        enabled: false
  datasource:
    db-kind: h2
    username: sa
    password:
    jdbc:
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
  hibernate-orm:
    database:
      generation: update